version: "3"

services:
  Product-Service:
    image: patmilk/productmicro:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  Repository-Service:
    image: patmilk/product_database:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge