version: "3"

services:
  product-service:
    image: patmilk/product_microservice:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  repository-service:
    image: patmilk/product_database_microservice:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

  order-service:
    image: patmilk/order_microservice:latest
    ports:
      - "8082:8082"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge